-- Add Rhode Island cities to service_areas table
INSERT INTO service_areas (name) VALUES
    ('Providence'),
    ('Warwick'),
    ('Cranston'),
    ('Pawtucket'),
    ('East Providence'),
    ('Woonsocket'),
    ('Newport'),
    ('Central Falls'),
    ('Westerly'),
    ('North Providence'),
    ('South Kingstown'),
    ('West Warwick'),
    ('Cumberland'),
    ('Johnston'),
    ('North Kingstown'),
    ('Bristol'),
    ('Lincoln'),
    ('Smithfield'),
    ('Portsmouth'),
    ('Barrington'),
    ('Middletown'),
    ('Narragansett'),
    ('East Greenwich'),
    ('Warren'),
    ('Coventry'),
    ('Tiverton'),
    ('Burrillville'),
    ('North Smithfield'),
    ('Exeter'),
    ('Hopkinton'),
    ('Richmond'),
    ('Charlestown'),
    ('Scituate'),
    ('Glocester'),
    ('West Greenwich'),
    ('Foster'),
    ('Jamestown'),
    ('Little Compton'),
    ('New Shoreham')
ON CONFLICT (name) DO NOTHING; 